### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by ActaV-N** [JunbaeJs/junbae-mode#6]
|name|about|title|labels|assignees|
|--|--|--|--|--|
|Ted Chiang|Parrots may need some friends so that they don't feel loneliness. Junbae is a parrot who needs friends too! |Ted Chiang|friend|@changchanghwang|

### Describe the feature 
Junbae needs friends! Please make Junbae's friends like Changsik, Hwangdal, Hwanghae.

### Expected behavior 
If you type more and more, the other parrots will be appeared like Junbae so that Junbae can hang out with other parrots. 

### Example Code
IDK. XD

### Information
Version[e.g. v0.1.0]: beta version
OS[e.g. iOS]: Any OS where vscode can be run
Browser[e.g. chrome 62]: Any browser where vscode can be run

**Comment by changchanghwang** [comment]
It is not necessary right now. but I'll think abt your opinion. thanks
